# Generated by Django 3.2.8 on 2021-10-05 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subreddits', '0002_subreddit_name'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subreddit',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='subreddits.subreddit'),
            preserve_default=False,
        ),
    ]
