# Generated by Django 3.2.8 on 2021-10-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subreddits', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subreddits',
            field=models.ManyToManyField(blank=True, related_name='users_subreddits', to='subreddits.Subreddit'),
        ),
    ]
