# Generated by Django 3.2.8 on 2021-10-19 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_played_song',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='theme_choice',
            field=models.CharField(choices=[('theme_one.css', 'One'), ('theme_two.css', 'Two'), ('theme_three.css', 'Three'), ('theme_four.css', 'Four'), ('theme_light.css', 'Light'), ('theme_dark.css', 'Dark')], default='theme_three.css', max_length=15),
        ),
    ]
