[tool.poetry]
name = "q4-capstone-group-10"
version = "0.1.0"
description = ""
authors = ["Michael Vitollo <ace51689@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
Django = "^3.2.8"
django-environ = "^0.7.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
